name: notify slack
on: workflow_dispatch
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/notify-slack
        with:
          message: Holaaa
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        id: saludar
      - uses: ./.github/actions/notify-slack
        with:
          message: Adi√≥ooss!
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          type: danger
        id: despedir
      - run: echo ${{ steps.saludar.outputs.sent_message }}
      - run: echo ${{ steps.despedir.outputs.sent_message }}
